// Code generated by tooling; DO NOT EDIT.
package tag

import (
	"strings"

	"github.com/nomad-software/goat/internal/tk"

)



// SetFont sets the widget's font.
func (el *Tag) SetFont(font string, size string, styles ...string) {
	style := strings.Join(styles, " ")
	tk.Get().Eval("%s tag configure {%s} -font {{%s} %s %s}", el.GetParent().GetID(), el.GetID(), font, size, style)
}
