// Code generated by tooling; DO NOT EDIT.
package tag

import (
	"github.com/nomad-software/goat/internal/tk"

)



// AlightText aligns the text in different ways.
// See [option.align]
func (el *Tag) AlignText(align string) {
	tk.Get().Eval("%s tag configure {%s} -justify {%s}", el.GetParent().GetID(), el.GetID(), align)
}
