// Code generated by tooling; DO NOT EDIT.
package tag

import (
	"github.com/nomad-software/goat/internal/tk"

)



// SetBorderWidth sets border width.
func (el *Tag) SetBorderWidth(width int) {
	tk.Get().Eval("%s tag configure {%s} -borderwidth %d", el.GetParent().GetID(), el.GetID(), width)
}

// SetRelief sets the relief effect.
// See [option.relief] for relief values.
func (el *Tag) SetRelief(relief string) {
	tk.Get().Eval("%s tag configure {%s} -relief {%s}", el.GetParent().GetID(), el.GetID(), relief)
}
