// Code generated by tooling; DO NOT EDIT.
package tag

import (
	"github.com/nomad-software/goat/internal/tk"

)



// SetUnderline sets whether the text us underlined.
func (el *Tag) SetUnderline(underline bool) {
	tk.Get().Eval("%s tag configure {%s} -underline %v", el.GetParent().GetID(), el.GetID(), underline)
}

// SetUnderlineColor sets the underline foreground color.
// See [option.color] for color names.
// A hexadecimal string can be used too. e.g. #FFFFFF.
func (el *Tag) SetUnderlineColor(c string) {
	tk.Get().Eval("%s tag configure {%s} -underlinefg {%s}", el.GetParent().GetID(), el.GetID(), c)
}
