// Code generated by tooling; DO NOT EDIT.
package text

import (
	"github.com/nomad-software/goat/internal/tk"

	"github.com/nomad-software/goat/widget/scrollbar"
)




// AttachHorizontalScrollbar sets the horizontal scrollbar.
func (el *Text) AttachHorizontalScrollbar(bar *scrollbar.HorizontalScrollbar) {
	tk.Get().Eval("%s configure -xscrollcommand [list %s set]", el.GetID(), bar.GetID())
}

// AttachVerticalScrollbar sets the vertical scrollbar.
func (el *Text) AttachVerticalScrollbar(bar *scrollbar.VerticalScrollbar) {
	tk.Get().Eval("%s configure -yscrollcommand [list %s set]", el.GetID(), bar.GetID())
}
