// Code generated by tooling; DO NOT EDIT.
package arc

import (
	"fmt"

	"github.com/nomad-software/goat/internal/tk"

)



// SetDash sets the outline dash.
func (el *Arc) SetDash(one, two int, rest ...int) {
	str := ""
	for _, i := range rest {
		str += fmt.Sprintf(" %d", i)
	}
	tk.Get().Eval("%s itemconfigure %s -dash [list %d %d %s]", el.GetParent().GetID(), el.GetID(), one, two, str)
}
