// Code generated by tooling; DO NOT EDIT.
package spinbox

import (
	"github.com/nomad-software/goat/internal/tk"

	"github.com/nomad-software/goat/widget/scrollbar"
)




// AttachHorizontalScrollbar sets the horizontal scrollbar.
func (el *Spinbox) AttachHorizontalScrollbar(bar *scrollbar.HorizontalScrollbar) {
	tk.Get().Eval("%s configure -xscrollcommand [list %s set]", el.GetID(), bar.GetID())
}


