// Code generated by tooling; DO NOT EDIT.
package entry

import (

	"github.com/nomad-software/goat/tk"
	"github.com/nomad-software/goat/widget/scrollbar"
)




// SetHorizontalScrollbar sets the horizontal scrollbar.
func (el *Entry) SetHorizontalScrollbar(bar *scrollbar.HorizontalScrollbar) {
	tk.Get().Eval("%s configure -command [list %s xview]", bar.GetID(), el.GetID())
	tk.Get().Eval("%s configure -xscrollcommand [list %s set]", el.GetID(), bar.GetID())
}


