// Code generated by tooling; DO NOT EDIT.
package tag

import (
	"github.com/nomad-software/goat/internal/widget/ui/element"
)



type deleter interface {
	DeleteItem(item element.Element)
}

// Delete removes this item from the canvas.
func (el *Tag) Delete() {
	el.GetParent().(deleter).DeleteItem(el)
}
