package output

import (
	"bytes"
	"html/template"

	"github.com/nomad-software/goat/internal/tools/generate/file/method"
	"github.com/nomad-software/goat/log"
)

const (
	outputTmpl = `// Code generated by tooling; DO NOT EDIT.
package {{.PkgName}}

import (
	"{{.ImportPath}}"
)

{{range .Methods}}{{println .}}
{{end}}`
)

func Create(o *method.Output) []byte {
	tmpl, err := template.New("file").Parse(outputTmpl)
	if err != nil {
		log.Error(err)
		return nil
	}

	buf := new(bytes.Buffer)
	tmpl.Execute(buf, o)

	return buf.Bytes()
}
