// Code generated by tooling; DO NOT EDIT.
package window

import (
	"github.com/nomad-software/goat/internal/element/common/color"
)

// SetBackgroundColor sets the background color.
// See [element.color] for color names.
func (ele *Window) SetBackgroundColor(c string) {
	color.SetBackgroundColor(ele.GetID(), c)
}

