// Code generated by tooling; DO NOT EDIT.
package window

import (
	"github.com/nomad-software/goat/tk"
)






// SetBackgroundColor sets the background color.
// See [widget.option.color] for color names.
// A hexadecimal string can be used too. e.g. #FFFFFF.
func (el *Window) SetBackgroundColor(c string) {
	tk.Get().Eval("%s configure -background {%s}", el.GetID(), c)
}


