// Code generated by tooling; DO NOT EDIT.
package window

import (
	"github.com/nomad-software/goat/tk"
)






// SetBackgroundColor sets the background color.
// See [element.color] for color names.
func (ele *Window) SetBackgroundColor(c string) {
	tk.Get().Eval("%s configure -background %s", ele.GetID(), c)
}


