// Code generated by tooling; DO NOT EDIT.
package window

import (
	"github.com/nomad-software/goat/tk"
)




// SetHeight sets the height.
func (el *Window) SetHeight(h int) {
	tk.Get().Eval("%s configure -height %d", el.GetID(), h)
}
