// Code generated by tooling; DO NOT EDIT.
package labelframe

import (
	"github.com/nomad-software/goat/tk"
)




// SetPadding sets the padding.
func (el *LabelFrame) SetPadding(p int) {
	tk.Get().Eval("%s configure -padding %d", el.GetID(), p)
}
