// Code generated by tooling; DO NOT EDIT.
package labelframe

import (
	"github.com/nomad-software/goat/tk"
)




// SetPadding sets the padding.
func (el *LabelFrame) SetUnderline(index int) {
	tk.Get().Eval("%s configure -underline %d", el.GetID(), index)
}
